# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Products' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Products
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'FirebaseUI/Storage'
pod 'M13Checkbox', '~> 3.3.2'
pod 'NotificationBannerSwift'
  target 'ProductsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
